DATASOURCE:
  # YAML에서 특수문자(:, & 등)가 들어간 URL은 따옴표("")로 감싸는 것이 안전합니다.
  URL: "jdbc:mysql://localhost:3306/ct?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true"
  USERNAME: ct
  PASSWORD: 1234